### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by yoloyachtclub** [HowieDuhzit/Duhzit-Wit-Tools#1]
Trying to install, seems its miss dependencies (asking for PIL). I tried opening blender with admin permissions and reinstalling and that didn't work. I did try manually installing some of the dependencies but I'm still seeing problems (menu buttons linking discord/patreon not showing up). 
  
I'm wondering if you mean something different by installing as admin?

**Comment by HowieDuhzit** [comment]
Hmm what version of Blender are you using?

**Comment by metapea** [comment]
I've been getting the same thing, on the more recent 4.0's versions.
```
Traceback (most recent call last):
  File "X:\Steam\steamapps\common\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "X:\Steam\steamapps\common\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DWTools\__init__.py", line 26, in <module>
    from .properties import *
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DWTools\properties.py", line 3, in <module>
    from .functions import *
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DWTools\functions.py", line 14, in <module>
    from PIL import Image, ImageChops
ModuleNotFoundError: No module named 'PIL'
```

**Comment by Richetoku** [comment]
These worked for me:
"C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin\python.exe" -m pip install pillow
"C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin\python.exe" -m pip install opencv-python
"C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin\python.exe" -m pip install opencv-contrib-python
